jobs:
- name: build
  plan:
  - get: concourse
    trigger: true
    params:
      globs: [none]
      include_source_tarball: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: karalabe/xgo-latest
          tag: latest
      inputs:
      - name: concourse
      caches:
      - path: deps-cache
      outputs:
      - name: artifacts
      - name: ver
      params:
        TARGETS: linux/arm-5 linux/arm-6 linux/arm-7 linux/arm64 android/* ios/*
      run:
        path: bash
        args:
        - -exc
        - |
          target=$PWD/artifacts

          mkdir -p /build
          rm -rf /deps-cache
          ln -s $PWD/deps-cache /deps-cache

          mkdir -p concourse-source/src/github.com/concourse/
          tar \
            -zx \
            -C concourse-source/src/github.com/concourse/ \
            -f concourse/source.tar.gz
          
          mv -v \
            concourse-source/src/github.com/concourse/concourse-concourse-* \
            concourse-source/src/github.com/concourse/concourse

          cd concourse-source
          export EXT_GOPATH=$PWD

          cd /build
          /build.sh github.com/concourse/concourse/fly
          cp -v fly-* $target/

  - put: fly-release
    params:
      name: concourse/tag
      tag: concourse/tag
      globs:
      - artifacts/*

resources:
- name: concourse
  type: github-release
  source:
    owner: concourse
    repository: concourse
    access_token: ((github.access_token))
- name: fly-release
  type: github-release
  source:
    owner: timotto
    repository: concourse-fly-arm
    access_token: ((github.access_token))
